### ISSUE TITLE
Use Case: Hash-file Write Feature Request

### ISSUE THREAD

**Issue by rocket4321** [HobbyOneDroid/HashDroid#7]
Personally, I had an issue with SD-card corruption and could not find a Google Play Store app what would allow me to scan thru an entire folder and examine every file's matching hash value to a pre-calculated value already saved in a properties file. HashDroid was the closest I could find, but still had to be performed on a single file at a file and could not be saved for re-evaluation within the app.

So I'm interested if anyone else would see value in these features:

-) Write Hash file: Save hash value calculated from file into a hash file
>> Each hash file would only included 1 hash function's value, most likely CRC32, and would be named to avoid conflicts, such as "filename" plus ".hash"

-) Compare Calculated Hash to value in Hash file: Compare previously saved value in hash file to newly calculated hash and confirm no change. Identify all files that have altered hash value to user.

-) Perform above functions for an entire directory, and/or all sub-directories, if requested by user

I'm developing these features as a learning experience for myself, but am eager to hear from others about it's value to the app for the community.

**Comment by rocket4321** [comment]
No interest?

**Comment by rocket4321** [comment]
Looks like this is a dead project......

**Comment by ohhai** [comment]
Came here to ask for the same - possibility for selecting multiple files at once (or entire directory). Have same task to transfer my files from phone to PC and then verify their integrity after that.
